name: aurora_push_example
description: Demonstrates how to use the aurora_push_service plugin.
version: 0.2.0+2
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  aurora_push_service:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^14.1.1
  flutter_local_notifications_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: b3679eec5067806020b01c388894ad536a278a98
      path: packages/flutter_local_notifications/flutter_local_notifications_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true